language: ruby
rvm:
  - 2.2.1

services:
  - postgresql

before_script:
  # Setup Test Database
  - psql -c 'create database helpy_test;' -U postgres

script:
  # Load database schema
  - bundle exec rake db:schema:load
  # Test suite
  - bundle exec rake
  # Brakeman security scanner
  - bundle exec brakeman -z
  # Check vulnerable gems
  - bundle exec bundle-audit check --update
  # Rubocop static code analyzer
  - bundle exec rubocop
  # SCSS analyzer
  - bundle exec scss-lint

cache: bundler

addons:
    code_climate:
        repo_token: 8aed69acf532241f5281042dc5b1a5d89ea9206773d079ce2de838a28f0f5041
