apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: helpy
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: helpy
    tier: cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: helpy
      tier: cache
  template:
    metadata:
      name: redis
      labels:
        app: helpy
        tier: cache
    spec:
      containers:
      - name: redis
        image: redis:4.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi        
        ports:
        - containerPort: 6379