tickets: true
forums: true
knowledgebase: true
parent_site: /parent-redirect.html
parent_company: Main Site

# Site Settings

site_url: http://support.yourdomain.com
site_name: Cheatsheet
product_name:

# Analytics and Tracking
google_analytics_id:
send_usage_data: true
admin_email: inbound.support@yourdomain.com


#Mail specific settings:
type: imap
server: "imap.gmail.com"
username: "inbound.support@yourdomain.com"
password: "somethingsecret"
port: 993
use_login: yes
ssl: yes
