# Toggle functionality (not fully implemented)
tickets: true
forums: true
knowledgebase: true

# Site Settings

parent_site: /parent-redirect.html # This tells Helpy how to provide a link back to your main site
parent_company: Main Site # This is the parent company your helpdesk is providing support for
site_url: http://support.yourdomain.com # This is the URL of your support site
site_name: Helpy Support # This is the name of your support site
site_tagline: Support and Helpdesk Software # This is the tagline of your support site
product_name: # This is the product name your are supporting
support_phone: # This is support number to be displayed

# Mandrill Account
mandrill_username: #Enter your Madrill username
mandrill_api_key: #Enter your Madrill API Key

# Analytics and Tracking
google_analytics_id: #Enter your analytics ID
send_usage_data: true
admin_email: inbound.support@yourdomain.com
from_email: inbound.support@yourdomain.com

# You must signup with each oauth provider you wish to support and add the ID and secret
# for each below:
#omniauth:
#  providers:
#    github:
#      id:
#      secret:
#    twitter:
#      id:
#      secret:
#    google:
#      id:
#      secret:
