master_settings:
  tickets: true
  forums: true
  knowledgebase: true
  parent_site: /parent-redirect.html
  parent_company: Main Site

development: &master_settings
  parent_site: /parent-redirect.html
  parent_company: Main Site

  site_url: http://localhost:3000
  site_name: CheatSheet Support
  product_name:
  admin_email: inbound.support@vertster.com
  send_email: false

  #Mail specific settings:
  type: imap
  server: "imap.gmail.com"
  username: "inbound.support@vertster.com"
  password: "QTwjx0aQuUgIzHkPlK9s"
  port: 993
  use_login: yes
  ssl: yes

test:
  <<: *non_production_settings

staging:
  site_name: Cheatsheet
  product_name:
  admin_email: inbound.support@vertster.com
  send_email: false

  #Mail specific settings:
  type: imap
  server: "imap.gmail.com"
  username: "inbound.support@vertster.com"
  password: "QTwjx0aQuUgIzHkPlK9s"
  port: 993
  use_login: yes
  ssl: yes

production: &master_settings

  # Site Settings

  site_url: http://cheatsheet.vertster.com
  site_name: Cheatsheet
  product_name:

  # Analytics and Tracking
  google_analytics_id:
  send_usage_data: true

  admin_email: inbound.support@vertster.com
  send_email: true

  #Mail specific settings:
  type: imap
  server: "imap.gmail.com"
  username: "inbound.support@vertster.com"
  password: "QTwjx0aQuUgIzHkPlK9s"
  port: 993
  use_login: yes
  ssl: yes
