development: &non_production_settings
  site_url: http://localhost:3004
  site_name: Cheatsheet
  product_name:
  admin_email: inbound.support@vertster.com
  send_email: false

  #Mail specific settings:
  type: imap
  server: "imap.gmail.com"
  username: "inbound.support@vertster.com"
  password: "QTwjx0aQuUgIzHkPlK9s"
  port: 993
  use_login: yes
  ssl: yes

test:
  <<: *non_production_settings

staging:
  site_name: Cheatsheet
  product_name:
  admin_email: inbound.support@vertster.com
  send_email: false

  #Mail specific settings:
  type: imap
  server: "imap.gmail.com"
  username: "inbound.support@vertster.com"
  password: "QTwjx0aQuUgIzHkPlK9s"
  port: 993
  use_login: yes
  ssl: yes

production:
  site_url: http://cheatsheet.vertster.com
  site_name: Cheatsheet
  product_name:   
  admin_email: inbound.support@vertster.com
  send_email: true

  #Mail specific settings:
  type: imap
  server: "imap.gmail.com"
  username: "inbound.support@vertster.com"
  password: "QTwjx0aQuUgIzHkPlK9s"
  port: 993
  use_login: yes
  ssl: yes
