# Toggle functionality (not fully implemented)
tickets: true
forums: true
knowledgebase: true

# Site Settings

parent_site: /parent-redirect.html # This tells Helpy how to provide a link back to your main site
parent_company: Main Site # This is the parent company your helpdesk is providing support for
site_url: http://support.yourdomain.com # This is the URL of your support site
site_name: Helpy Support # This is the name of your support site
site_tagline: Support and Helpdesk Software # This is the tagline of your support site
product_name: # This is the product name your are supporting
support_phone: # This is support number to be displayed

# Analytics and Tracking
google_analytics_id: #Enter your analytics ID
send_usage_data: true

#Mail specific settings:
admin_email: inbound.support@yourdomain.com
from_email: inbound.support@yourdomain.com # This is the email that will be used for email replies (reply to)
send_email: true #send email or not

mail_service: :mandrill # :sendgrid :cloudmailin, :postmark, :mandrill, :mailgun
smtp_mail_username: # Enter your SMTP email username
smtp_mail_password: # Enter your SMTP email password
mail_smtp: 'smtp.mandrillapp.com' #Enter the server address for your SMTP server
mail_port: 587 #Enter the port of your SMTP server
mail_domain: #Enter your the heroku.com if you are on heroku, otherwise enter your domain

# Allow users to create an account and/or sign in with email/password
# If you choose no, you must set up oauth below.  There will still be a hidden login screen
# For admin users
allow_standard_login: true

# You must sign up with each oauth provider you wish to support and add the ID and secret
# for each below:
omniauth:
  providers:
    github:
      id:
      secret:
    twitter:
      id:
      secret:
    google_oauth2:
      id:
      secret: 
